apiVersion: projectcalico.org/v3
kind: BGPPeer
metadata:
  name: remote-rr-clustera
spec:
  nodeSelector: route-reflector == 'true'
  # set IP of the remote route reflector to peer with
  peerIP: 
  asNumber: 64512
  keepOriginalNextHop: true
---

apiVersion: projectcalico.org/v3
kind: BGPPeer
metadata:
  name: remote-rr-clusterc
spec:
  nodeSelector: route-reflector == 'true'
  # set IP of the remote route reflector to peer with
  peerIP: 
  asNumber: 64514
  keepOriginalNextHop: true
